# Generated by Django 4.1.5 on 2023-03-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_swims', '0002_alter_customertype_age_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimcustomer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
