# Generated by Django 4.1.5 on 2023-03-10 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_swims', '0003_swimcustomer_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerType',
            new_name='AgeGroup',
        ),
        migrations.RenameModel(
            old_name='SwimCustomer',
            new_name='SwimPrice',
        ),
        migrations.AddField(
            model_name='swimschedule',
            name='price',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='public_swims.swimprice'),
            preserve_default=False,
        ),
    ]
