# Generated by Django 4.1.5 on 2023-03-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_swims', '0004_rename_customertype_agegroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swimprice',
            name='swim',
        ),
    ]
