# Generated by Django 4.1.5 on 2023-03-10 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_swims', '0005_remove_swimprice_swim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swimschedule',
            name='price',
        ),
        migrations.AddField(
            model_name='swimprice',
            name='schedule',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='public_swims.swimschedule'),
            preserve_default=False,
        ),
    ]
