# Generated by Django 4.1.5 on 2023-03-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swimling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(null=True)),
                ('school_role_number', models.CharField(blank=True, max_length=6, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('wp_student_id', models.IntegerField(null=True)),
            ],
        ),
    ]
