# Generated by Django 4.1.5 on 2023-03-08 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swimmer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimling',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_swimlings', to=settings.AUTH_USER_MODEL),
        ),
    ]
