# Generated by Django 4.1.5 on 2023-03-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('orders', '0001_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='PublicClasses',
        ),
        migrations.AlterModelOptions(
            name='publicclasses',
            options={'ordering': ['name'], 'verbose_name_plural': 'Public Classes'},
        ),
        migrations.RenameIndex(
            model_name='publicclasses',
            new_name='lessons_pub_id_76d8ab_idx',
            old_name='lessons_pro_id_9a2e47_idx',
        ),
        migrations.RenameIndex(
            model_name='publicclasses',
            new_name='lessons_pub_name_6eed57_idx',
            old_name='lessons_pro_name_fb7aec_idx',
        ),
        migrations.RenameIndex(
            model_name='publicclasses',
            new_name='lessons_pub_created_8ce03a_idx',
            old_name='lessons_pro_created_6b811b_idx',
        ),
    ]
